train_indices : null
num_workers: 16
num_epochs: 75
batch_size: 4
num_steps_per_epoch: 250
lr: 0.000001
weight_decay: 0.0001
sched: 
    max_epoch: 75
    warmup_max: 10
    multiplier: 100
    update_interval: "epoch"
    update_freq: 1
loss: 
    normalize_fct: null
    reduction: "mean"
    alpha_CE: 0.5
    weighted_CE: false
    n_classes: 2
    scale_loss: false

# The following lines are added to the original config file for VAAL
additional_params: 
    module: "VAAL"
    latent_dim: 32
    beta: 1
    num_adv_steps: 1
    num_vae_steps: 2
    adversary_param: 1
    
transform:
    rotation: 10
    gauss_noise: 
        std: 0.01
    resize: (352, 736)
    is_train: True
sampling:
    budget: 40
    num_cycles: 7
patience: 10