strategy: "TTA"
sampling_params: 
  num_inferences: 5
  uncertainty_metric: "JSD"
  alpha: 0.5
  transform:
    rotation: 10
    gauss_noise: 
        std: 0.01
    resize: (352, 736)
    is_train: True  # Data augmentation is only applied to training data